name: Populate Level of the Day (Docker)

on:
  schedule:
    # Run at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      target_date:
        description: 'Target date for level generation (YYYY-MM-DD format, optional)'
        required: false
        type: string

jobs:
  populate-level:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t marcel-games-backend .

    - name: Run populate script in Docker
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        if [ -n "${{ github.event.inputs.target_date }}" ]; then
          docker run --rm \
            -e DATABASE_URL="${DATABASE_URL}" \
            marcel-games-backend \
            go run cmd/populate-level-of-the-day/main.go "${{ github.event.inputs.target_date }}"
        else
          docker run --rm \
            -e DATABASE_URL="${DATABASE_URL}" \
            marcel-games-backend \
            go run cmd/populate-level-of-the-day/main.go
        fi

    - name: Notify on success
      if: success()
      run: echo "Level of the day populated successfully using Docker!"

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Level of the Day Population Failed (Docker)',
            body: `The Docker-based GitHub Action to populate the level of the day failed.\n\nWorkflow run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
            labels: ['bug', 'automated']
          })
